export const GET_ALL_TODOS_REQUEST = 'GET_ALL_TODOS_REQUEST';
export const GET_ALL_TODOS_SUCCESS = 'GET_ALL_TODOS_SUCCESS';
export const GET_ALL_TODOS_FAIL = 'GET_ALL_TODOS_FAIL';

export const ADD_NEW_TODO_REQUEST = 'ADD_NEW_TODO_REQUEST';
export const ADD_NEW_TODO_SUCCESS = 'ADD_NEW_TODO_SUCCESS';
export const ADD_NEW_TODO_FAIL = 'ADD_NEW_TODO_FAIL';

export const TODO_COMPLETE_REQUEST = 'TODO_COMPLETE_REQUEST';
export const TODO_COMPLETE_SUCCESS = 'TODO_COMPLETE_SUCCESS';
export const TODO_COMPLETE_FAIL = 'TODO_COMPLETE_FAIL';
export const TODO_COMPLETE_RESET = 'TODO_COMPLETE_RESET';

export const TODO_INCOMPLETE_REQUEST = 'TODO_INCOMPLETE_SUCCESS';
export const TODO_INCOMPLETE_SUCCESS = 'TODO_INCOMPLETE_REQUEST';
export const TODO_INCOMPLETE_FAIL = 'TODO_INCOMPLETE_FAIL';
export const TODO_INCOMPLETE_RESET = 'TODO_INCOMPLETE_RESET';

export const TODO_DELETE = 'TODO_DELETE';
export const TODO_DELETE_FAIL = 'TODO_DELETE_FAIL';
export const TODO_DELETE_RESET = 'TODO_DELETE_RESET';

export const TODO_UPDATE_REQUEST = 'TODO_UPDATE_REQUEST';
export const TODO_UPDATE_SUCCESS = 'TODO_UPDATE_SUCCESS';
export const TODO_UPDATE_FAIL = 'TODO_UPDATE_FAIL';
export const TODO_UPDATE_RESET = 'TODO_UPDATE_RESET';
